[Feature:RainbowGrades] Adding Link to Gradeables
Submitty/RainbowGrades pull request #83
Opened 2024-11-06 23:17 UTC by ryvaru

Closes #10433 (https://github.com/Submitty/Submitty/issues/10433)

**What is the current behavior?**
Currently, students can only see their grade for a specific gradeable on Rainbow Grades, and would have to search through gradeables to see their full report.

**What is the new behavior?**
Now, when students see their grade on Rainbow Grades, they can just click on it and it sends them to see their full report directly. This is more convenient and helpful for students.

**Other information?**
This PR fixes and reimplements the code made in PR #81.

To test: Go to a course --> Make sure Rainbow Grades viewing is enabled --> Generate Grade Summaries --> Web-Based Rainbow Grades Generation --> (Drop items into bucket and display at least grade_summary and grade_details) --> Build --> View changes on Rainbow Grades by clicking on a gradeable.

2024-12-03 20:41 UTC, Kush-Raval approved these changes
The code changes generally make sense. The URL building should probably be relooked at for security reasons. 
But everything else looks good.

2024-12-07 08:58 UTC, ziesski commented
@ryvaru Could you give https://github.com/Submitty/RainbowGrades/pull/81 and @oliiso credit for initial starting point of the work?

2024-12-10 00:32 UTC, ryvaru commented
> @ryvaru Could you give #81 and @oliiso credit for initial starting point of the work?

Of course, I updated the PR description to give credit to @oliiso at the very top.

2024-12-12 18:15 UTC, bmcutler requested changes
This fails & crashes when I run rainbow grades on my local machine vs on the server.

2024-12-12 18:15 UTC, bmcutler commented on output.cpp
> +  const char* reportsDir = std::getenv("REPORTS_DIRECTORY");
this directory does not exist when instructor runs rainbow grades locally.

2026-06-02 15:20 UTC, closed without merging

2026-06-02 15:20 UTC, bmcutler commented
thanks for the contribution, merged as part of #88